### PR TITLE
Automatically publish binaries to Github Release Assets through Github Action

### PR DESCRIPTION
**Pull request by k997**

### CODE REVIEW

**Comment by k997** [comment]
This pr supports x86_64-pc-windows-msvc, aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, x86_64-apple-darwin and aarch64-apple-darwin.

**Comment by 0xfederama** [comment]
thank you!

**Comment by k997** [comment]
> thank you!

My pleasure. And don't forget to enable write permissions so that  actions can upload binaries.

**Comment by 0xfederama** [comment]
I think the action does not even trigger, it says "This workflow has no runs yet." even if I enabled read and write permissions

**Comment by k997** [comment]
> I think the action does not even trigger, it says "This workflow has no runs yet." even if I enabled read and write permissions

It will run automatically when you create a release on main branch.

**Comment by 0xfederama** [comment]
I thought it would run on push. Even better this way, thanks

**Comment by k997** [comment]
> I thought it would run on push. Even better this way, thanks

Now the actions works when push tags start with 'v'. You can just delete `tags: - "v*"` and comment out if statement below to make it run on push. And you should add `actions/upload-artifact` step so that you can download the compilation results. You can find more triggers in github actions document and more action steps in github marketplace.

```
on:
  push:
    branches:
      - master
#    tags:
#      - "v*"
# comment out it
# if: startsWith(github.ref, 'refs/tags/')
```

**Comment by 0xfederama** [comment]
I think it's better to make it run only when needed, so when a new release is manually created. If now it works like this it's perfect

**Pull request merged**
