### PR TITLE
Create release.yml

### PR DESCRIPTION
**Pull request by k997**
Automatically publish binaries to Github Release Assets through Github Action.

### CODE REVIEW

**Comment by k997** [comment]
> Automatically publish binaries to Github Release Assets through Github Action.

 Enable `Actions -> General->Workflow permissions->Read and write permissions` to make actions work properly.

**Comment by 0xfederama** [comment]
Does this PR build the code and zip it before pushing to github releases?
Does it also build it in release mode with `cargo build -r`?

**Comment by k997** [comment]
> Does this PR build the code and zip it before pushing to github releases?
> Does it also build it in release mode with `cargo build -r`?

Yeap. This action will take effect when you click to create a release on GitHub, then it build and release binaries automatically.

**Comment by 0xfederama** [comment]
Could you add also the option for arm macos?
Maybe also for arm linux and windows would be great

**Comment by k997** [comment]
> Could you add also the option for arm macos? Maybe also for arm linux and windows would be great

Currently the [rust-build/rust-build.action](https://github.com/rust-build/rust-build.action) I chose just supports x86/64. Let me see if I can find a replacement.

**Comment by 0xfederama** [comment]
@k997 did you find a way to compile also for arm?

**Pull request closed without merging**
